# goreleaser.yml
project_name: vault_exporter
build:
  binary: vault_exporter
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    files:
    - README.md
    - LICENSE
snapshot:
  name_template: snapshot-{{.Commit}}
